__default__:
    h_vmem: '4g'
    h_rt: '48:00:00'
    pe: 'smp 12'
    project: 'medium'

basecalling:
    h_vmem: '4g'
    h_rt: '96:00:00'
    pe: 'smp 24'
    project: 'medium'

ngmlr:
    h_vmem: '4g'
    h_rt: '72:00:00'
    pe: 'smp 24'
    project: 'medium'
