
# sample config
metafile: "metadata.txt"

# outputdir
outputdir: "/fast/projects/NB_CircleSeq/work/CircleSeq_data/CircleSeq/Nanopore/Celllines/Process"

hg38:
  genome:  "/fast/projects/cubit/current/static_data/annotation/GENCODE/33/GRCh38/GRCh38.p13.genome.fa"
  gtf: "/fast/projects/cubit/current/static_data/annotation/GENCODE/33/GRCh38/gencode.v33.annotation.gtf"

filtering:
  assembly:
    readlen: 10000
    qual: 20

params:
  mapping: "-E0.5 -x intractg"

threads: 16
